@startuml Hello World
!$AWS_DARK = true
' https://github.com/awslabs/aws-icons-for-plantuml/tree/main/dist

' left to right direction
skinparam linetype ortho

!define AWSPuml https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v18.0/dist
!include AWSPuml/AWSCommon.puml
!include AWSPuml/BusinessApplications/all.puml

!include AWSPuml/Groups/Generic.puml

!include AWSPuml/Storage/SimpleStorageService.puml
!include AWSPuml/General/AuthenticatedUser.puml
!include AWSPuml/General/User.puml
!include AWSPuml/Compute/Lambda.puml
!include AWSPuml/Database/DynamoDB.puml
!include AWSPuml/ApplicationIntegration/APIGateway.puml

GenericGroup(portfolio, "Portfolio"){
    AuthenticatedUser(user_auth, "Website (Auth) User", "Web Browser", "Access Web Ui and performs actions")

    User(user_unauth, "Website (Unauth) User", "Web Browser", "Access Web Ui and performs actions")


    Lambda(fn_portfolio_ui, "Portfolio Ui", "Svelte + Lambda", "Standalone lambda function deployed from svelte ui. Visualises the portfolio website")

    APIGateway(test_api, "Test API", "AWS APIGW", "Routes Traffic")

    DynamoDB(db_portfolio, "Portfolio Database", "DynamoDB", "Stored all portfolio details")
}

@enduml