steps:
  - name: "gcr.io/cloud-builders/git"
    id: "Get Previous Commit"
    entrypoint: "/bin/bash"
    args:
      - "-c"
      - |
        git log --pretty=format:'%H' -n 2 > /workspace/commits.txt
        echo "PREVIOUS_COMMIT_SHA=$(sed -n '2p' /workspace/commits.txt)" >> /workspace/env_vars.txt

  - name: "gcr.io/cloud-builders/git"
    id: "Get Current Commit"
    entrypoint: "/bin/bash"
    args:
      - "-c"
      - echo "COMMIT_SHA=$(git rev-parse HEAD)" >> /workspace/env_vars.txt

  - name: "ubuntu"
    id: "Detect Changes"
    entrypoint: "/bin/bash"
    args:
      - "-c"
      - |
        source /workspace/env_vars.txt
        git diff --name-only $PREVIOUS_COMMIT_SHA $COMMIT_SHA > /workspace/changed_files.txt

  - name: "gcr.io/cloud-builders/docker"
    id: "Build Changed Dockerfiles"
    entrypoint: "/bin/bash"
    args:
      - "-c"
      - |
        for dir in $(cat /workspace/changed_dirs.txt); do
          cd $dir
          docker build -t gcr.io/$PROJECT_ID/$dir:$COMMIT_SHA .
          docker push gcr.io/$PROJECT_ID/$dir:$COMMIT_SHA
          cd ..
        done
