steps:
  - name: gcr.io/cloud-builders/git
    args: [fetch, --depth=2]

  - name: "gcr.io/cloud-builders/git"
    id: "Get Previous Commit"
    entrypoint: "/bin/bash"
    args:
      - "-c"
      - |
        echo $(git diff --name-only HEAD~1 HEAD | grep services | cut -d "/" -f 2 | uniq) > /workspace/changed_dirs.txt

  - name: "gcr.io/cloud-builders/docker"
    id: "Build Changed Dockerfiles"
    entrypoint: "/bin/bash"
    args:
      - "-c"
      - |
        for dir in $(cat /workspace/changed_dirs.txt); do
          cd $dir
          docker build -t gcr.io/$PROJECT_ID/$dir:$COMMIT_SHA .
          docker push gcr.io/$PROJECT_ID/$dir:$COMMIT_SHA
          cd ..
        done
