name: "Build and Push Docker Image"
on:
  push:
    paths:
      - "services/**"
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        run: |
          CHANGED_DIRS=$(git diff --dirstat=files,0 HEAD^..HEAD services/ | cut -d '%' -f 2 | cut -d '/' -f 2)
          for DIR in $CHANGED_DIRS; do
            IMAGE_NAME="dknathalage/personal:$DIR"
            docker build -t $IMAGE_NAME services/$DIR
            docker push $IMAGE_NAME
          done
