name: "Build and Push Docker Image"
on:
  push:
    paths:
      - "services/**"
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        run: |
          CHANGED_DIRS=$(git diff --name-only origin/main HEAD | grep services | cut -d/ -f2 | uniq)
          for DIR in $CHANGED_DIRS; do
            docker buildx build --platform linux/amd64,linux/arm64 -t $DOCKER_USERNAME/personal:$DIR --push services/$DIR
          done
