name: "CICD Pipeline"
on:
  push:
    # paths:
    #   - "services/**"
    branches:
      - main

jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        run: |
          CHANGED_DIRS=$(git diff --name-only HEAD~1 HEAD | grep services | cut -d/ -f2 | uniq)
          echo "Changed directories: $CHANGED_DIRS"
          for DIR in $CHANGED_DIRS; do
            docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCKER_USERNAME }}/personal:$DIR --push services/$DIR
          done

  helm-install:
    needs: build-images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: "1.18.8"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: "3.3.0"

      # login to gke cluster
      - name: Login to GKE
        uses: google-github-actions/auth@v0.2.0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT }}
          export_default_credentials: true

      # print kubectl context
      - name: Print kubectl context
        run: kubectl config current-context
