name: "CICD Pipeline"
on:
  push:
    # paths:
    #   - "services/**"
    branches:
      - main

jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        run: |
          CHANGED_DIRS=$(git diff --name-only HEAD~1 HEAD | grep services | cut -d/ -f2 | uniq)
          echo "Changed directories: $CHANGED_DIRS"
          for DIR in $CHANGED_DIRS; do
            docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCKER_USERNAME }}/personal:$DIR --push services/$DIR
          done

  helm-install:
    needs: build-images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT }}

      - uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: workload-cluster
          location: ${{ secrets.GCP_REGION }}
          credentials: ${{ secrets.GCP_SA_KEY }}

      - name: Get system pods
        run: |
          kubectl get pods -n kube-system
