name: Build Infrastructure

on:
  push:
    branches:
      - main
    paths:
      - "infra/**"

jobs:
  infra:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Configure Environment Variables
        run: |
          echo "GCP_PROJECT=${{ secrets.GCP_PROJECT }}" >> $GITHUB_ENV
          echo "GCP_REGION=${{ secrets.GCP_REGION }}" >> $GITHUB_ENV

      - name: Terraform Initialize
        run: terraform init -backend-config="bucket=${{ secrets.GCP_SA_KEY }}"

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Apply
        run: terraform apply -auto-approve
