name: Build Infrastructure

on:
  push:
    branches:
      - main
    paths:
      - "infra/**"

jobs:
  infra:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Initialize
        run: |
          cd infra
          terraform init -var "gcp_project=${{ secrets.GCP_PROJECT }}" -var "gcp_region=${{ secrets.GCP_REGION }}" -var "gcp_sa_key=${{ secrets.GCP_SA_KEY }}"

      - name: Terraform Validate
        run: |
          cd infra
          terraform validate -var "gcp_project=${{ secrets.GCP_PROJECT }}" -var "gcp_region=${{ secrets.GCP_REGION }} -var "gcp_sa_key=${{ secrets.GCP_SA_KEY }}"

      - name: Terraform Apply
        run: |
          cd infra
          terraform apply -auto-approve -var "gcp_project=${{ secrets.GCP_PROJECT }}" -var "gcp_region=${{ secrets.GCP_REGION }} -var "gcp_sa_key=${{ secrets.GCP_SA_KEY }}"
